/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as WorkflowIndexImport } from './routes/workflow/index'
import { Route as TasksIndexImport } from './routes/tasks/index'
import { Route as TasksTaskIdImport } from './routes/tasks/$taskId'
import { Route as TasksParentIdSubtaskIdImport } from './routes/tasks/$parentId/$subtaskId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WorkflowIndexRoute = WorkflowIndexImport.update({
  id: '/workflow/',
  path: '/workflow/',
  getParentRoute: () => rootRoute,
} as any)

const TasksIndexRoute = TasksIndexImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRoute,
} as any)

const TasksTaskIdRoute = TasksTaskIdImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => rootRoute,
} as any)

const TasksParentIdSubtaskIdRoute = TasksParentIdSubtaskIdImport.update({
  id: '/tasks/$parentId/$subtaskId',
  path: '/tasks/$parentId/$subtaskId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdImport
      parentRoute: typeof rootRoute
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksIndexImport
      parentRoute: typeof rootRoute
    }
    '/workflow/': {
      id: '/workflow/'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof WorkflowIndexImport
      parentRoute: typeof rootRoute
    }
    '/tasks/$parentId/$subtaskId': {
      id: '/tasks/$parentId/$subtaskId'
      path: '/tasks/$parentId/$subtaskId'
      fullPath: '/tasks/$parentId/$subtaskId'
      preLoaderRoute: typeof TasksParentIdSubtaskIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks': typeof TasksIndexRoute
  '/workflow': typeof WorkflowIndexRoute
  '/tasks/$parentId/$subtaskId': typeof TasksParentIdSubtaskIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks': typeof TasksIndexRoute
  '/workflow': typeof WorkflowIndexRoute
  '/tasks/$parentId/$subtaskId': typeof TasksParentIdSubtaskIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/': typeof TasksIndexRoute
  '/workflow/': typeof WorkflowIndexRoute
  '/tasks/$parentId/$subtaskId': typeof TasksParentIdSubtaskIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tasks/$taskId'
    | '/tasks'
    | '/workflow'
    | '/tasks/$parentId/$subtaskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tasks/$taskId'
    | '/tasks'
    | '/workflow'
    | '/tasks/$parentId/$subtaskId'
  id:
    | '__root__'
    | '/'
    | '/tasks/$taskId'
    | '/tasks/'
    | '/workflow/'
    | '/tasks/$parentId/$subtaskId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TasksTaskIdRoute: typeof TasksTaskIdRoute
  TasksIndexRoute: typeof TasksIndexRoute
  WorkflowIndexRoute: typeof WorkflowIndexRoute
  TasksParentIdSubtaskIdRoute: typeof TasksParentIdSubtaskIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TasksTaskIdRoute: TasksTaskIdRoute,
  TasksIndexRoute: TasksIndexRoute,
  WorkflowIndexRoute: WorkflowIndexRoute,
  TasksParentIdSubtaskIdRoute: TasksParentIdSubtaskIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/tasks/$taskId",
        "/tasks/",
        "/workflow/",
        "/tasks/$parentId/$subtaskId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/tasks/$taskId": {
      "filePath": "tasks/$taskId.tsx"
    },
    "/tasks/": {
      "filePath": "tasks/index.tsx"
    },
    "/workflow/": {
      "filePath": "workflow/index.tsx"
    },
    "/tasks/$parentId/$subtaskId": {
      "filePath": "tasks/$parentId/$subtaskId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
